let x = +prompt("Enter the first number: ");
let y = +prompt("Enter the second number: ");
let z = +prompt("Enter the third number: ");
let arr = [x, y, z];
let res = (x + y + z) / arr.length;
alert("Your result is " + res);
console.log(x);
console.log(y);
console.log(z);
console.log("Your result is " + res);
